### ISSUE TITLE
「评论」当Emby、Plex、Jellyfin遇上阿里云盘🎬

### ISSUE THREAD

**Issue by Kimentanm** [Kimentanm/blog-gitalk-comment#25]
页面：https://blog.kimen.com.cn/pages/5ee34a/

**Comment by sjy5270882** [comment]
大神可否吧第二步群晖里面通过docker然后用rclone挂载阿里云盘为本地磁盘，步骤详细一点，小白有点不知道怎么操作了

**Comment by Kimentanm** [comment]
> @sjy5270882
> 大神可否吧第二步群晖里面通过docker然后用rclone挂载阿里云盘为本地磁盘，步骤详细一点，小白有点不知道怎么操作了

我手里也没有群晖不知道咋写😂  
你可以参考一下这篇文章[群晖 NAS 挂载 Google Drive 共享云端硬盘（团队盘）](https://www.sheyilin.com/2020/04/docker-rclone-proxy)
把GoogleDrive换成Webdav就行了，镜像可以用docker-rclone-proxy也可以用docker-rclone，用docker-rclone-proxy的话要把proxy关了

**Comment by Joyace** [comment]
为什么我挂载之后宿主机能正常看到文件，plex里面添加资料库却没有任何文件呢，jellyfin也一样

**Comment by Kimentanm** [comment]
> @Joyace
> 为什么我挂载之后宿主机能正常看到文件，plex里面添加资料库却没有任何文件呢，jellyfin也一样

plex和jellyfin是直接装的还是通过docker装的呢？

**Comment by Joyace** [comment]
> @Kimentanm
> > @Joyace
> > 为什么我挂载之后宿主机能正常看到文件，plex里面添加资料库却没有任何文件呢，jellyfin也一样
> 
> plex和jellyfin是直接装的还是通过docker装的呢？

通过docker装的

**Comment by Kimentanm** [comment]
> @Joyace
> > @Kimentanm
> > > @Joyace
> > > 为什么我挂载之后宿主机能正常看到文件，plex里面添加资料库却没有任何文件呢，jellyfin也一样
> > 
> > plex和jellyfin是直接装的还是通过docker装的呢？
> 
> 通过docker装的

那挂载好的路径有没有映射到docker容器里面啊

**Comment by Joyace** [comment]
> @Kimentanm
> > @Joyace
> > > @Kimentanm
> > > > @Joyace
> > > > 为什么我挂载之后宿主机能正常看到文件，plex里面添加资料库却没有任何文件呢，jellyfin也一样
> > > 
> > > plex和jellyfin是直接装的还是通过docker装的呢？
> > 
> > 通过docker装的
> 
> 那挂载好的路径有没有映射到docker容器里面啊

映射了的  我把fuse也映射进plex还是不行

**Comment by Joyace** [comment]
``` YAML
version: '3'
services:
  rclone-od:
    image: mumiehub/rclone-mount
    container_name: rclone-od
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Shanghai
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./container/rclone:/root/.config/rclone
      - ./data/od:/mnt/mediaefs:shared
    environment:
      - RemotePath=od:oneindex
      - ConfigDir=/root/.config/rclone
      - ConfigName=rclone.conf
      - MountCommands=--allow-other --allow-non-empty --dir-cache-time 48h --poll-interval 5m --buffer-size 256M

  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Shanghai
    devices:
      - /dev/fuse
    volumes:
      - ./container/plex/transcode:/transcode
      - ./container/plex/config:/config
      - ./data:/data
    # ports:
    #   - 32400:32400
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped

  caddy:
    image: sashk/docker-caddy1
    container_name: caddy
    restart: always
    volumes:
      - ./container/caddy/:/etc/caddy/:ro
      - ./www:/www
    ports:
     - "3100:3100"
    depends_on:
      - plex
```
